version: '3.8'
services:

  frontend:
    image: 'bg3-build-frontend:latest'
    build:
      context: .
    container_name: frontend
    depends_on:
      - db
      - backend
    ports:
      - '4200:4200'

  backend:
    image: bg3-build-image
    container_name: backend
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://local_pgdb:5432/postgres
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres-admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
  pgadmin-data: