version: '3.8'
services:

  frontend:
    image: icdef/bg3-build-frontend:v1
    build:
      context: .
    container_name: frontend
    depends_on:
      - db
      - backend
    ports:
      - '4200:4200'

  backend:
    image: icdef/bg3-build-backend:v1
    container_name: backend
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://local_pgdb:5432/postgres
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: