services:

  frontend-prod:
    image: icdef/bg3-build-frontend:v2
    container_name: frontend
    depends_on:
      - db-prod
      - backend-prod
    ports:
      - '4200:4200'

  backend-prod:
    image: icdef/bg3-build-backend:v3
    container_name: backend
    depends_on:
      - db-prod
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://local_pgdb:5432/postgres
  #      - SPRING_PROFILES_ACTIVE=fetch-data

  db-prod:
    image: postgres
    container_name: local_pgdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-prod:/var/lib/postgresql/data

volumes:
  db-prod: