services:
  frontend-prod:
    image: icdef/bg3-build-frontend:v4
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      backend-prod:
        condition: service_healthy

  backend-prod:
    image: icdef/bg3-build-backend:v4
    container_name: backend
    depends_on:
      db-prod:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://local_pgdb:5432/postgres
      - SPRING_PROFILES_ACTIVE=fetch-data
    healthcheck:
      test: [ "CMD-SHELL", "THC_PATH=/actuator/health /cnb/process/health-check || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  db-prod:
    image: postgres
    container_name: local_pgdb
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres-admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-prod:
